### PR TITLE
Change of text on the DPUB 4 deliverable

### PR DESCRIPTION
**Pull request by iherman**
Outcome of the discussion on issue #12, the F2F meeting; see also https://github.com/w3c/dpubwg-charter/issues/12#issuecomment-286109507

### CODE REVIEW

**Comment by iherman** [comment]
/Cc @therealglazou @lrosenthol @dauwhe @astearns : any comments before this is merged?

**Comment by therealglazou** [comment]
@iherman I'm fine with the change

**Comment by lrosenthol** [comment]
@iherman Works for me, thanks!

**Comment by lrosenthol** [comment]
Me too.

**Comment by GarthConboy** [comment]
Ship it!

(as you might expect from me)  :-)

Best,
   Garth

On Tue, Mar 14, 2017 at 6:28 PM, Leonard Rosenthol <notifications@github.com

**Pull request merged**
