### PR TITLE
Added justifications for the input documents

### PR DESCRIPTION
**Pull request by iherman**

### CODE REVIEW

**Comment by iherman** [comment]
@TzviyaSiegman @GarthConboy : can you have a look at the justifications (and either edit it or accept the pull request)? Thanks.

**Review by TzviyaSiegman — COMMENTED** [review]
looks good to me. Is there any need to comment on collaboration with other WGs?

**Comment by iherman** [comment]
> looks good to me. Is there any need to comment on collaboration with other WGs?
> 
> 
> 
Yes, this should be done at some point, too.

**Comment by GarthConboy** [comment]
LGTM

Best,
   Garth

**Pull request merged**
